# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wn5tJHCOI_M5xkgngHtejEY-JC3eAjTs
"""

pip install pandas numpy matplotlib scikit-learn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

df = pd.read_csv("/content/naca0012_dataset.csv")

print(df.head())

print(df.info())
print(df.describe())

print(df.isnull().sum())

X = df[['Mach', 'Reynolds', 'Alpha']]

y = df[['CL', 'CD', 'CM']]

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

plt.figure(figsize=(8,5))

plt.scatter(df['Alpha'], df['CL'])

plt.xlabel("Angle of Attack")
plt.ylabel("Lift Coefficient CL")
plt.title("CL vs Alpha")

plt.grid(True)

plt.show()

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

linear_model = LinearRegression()
linear_model.fit(X_train, y_train)
y_pred_linear = linear_model.predict(X_test)

rmse_linear = np.sqrt(mean_squared_error(y_test, y_pred_linear))

r2_linear = r2_score(y_test, y_pred_linear)

print("Linear Regression RMSE:", rmse_linear)
print("Linear Regression R2:", r2_linear)

rf_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))

r2_rf = r2_score(y_test, y_pred_rf)

print("Random Forest RMSE:", rmse_rf)
print("Random Forest R2:", r2_rf)

print("Linear Regression R2:", r2_linear)
print("Random Forest R2:", r2_rf)

plt.figure(figsize=(8,5))

plt.scatter(y_test['CL'], y_pred_rf[:,0])

plt.xlabel("Actual CL")
plt.ylabel("Predicted CL")

plt.title("Actual vs Predicted CL")

plt.grid(True)

plt.show()

import joblib

joblib.dump(rf_model, "naca0012_model.pkl")

import joblib

model = joblib.load("naca0012_model.pkl")

new_input = [[0.25, 6000000, 8]]

joblib.dump(scaler, "scaler.pkl")

scaler = joblib.load("scaler.pkl")

new_input_scaled = scaler.transform(new_input)

prediction = model.predict(new_input_scaled)

print(prediction)

CL = prediction[0][0]
CD = prediction[0][1]
CM = prediction[0][2]

print("Predicted CL:", CL)
print("Predicted CD:", CD)
print("Predicted CM:", CM)

LD_ratio = CL / CD

print("Predicted L/D Ratio:", LD_ratio)

mach = float(input("Enter Mach number: "))
reynolds = float(input("Enter Reynolds number: "))
alpha = float(input("Enter Angle of Attack: "))

user_input = [[mach, reynolds, alpha]]

user_input_scaled = scaler.transform(user_input)

prediction = model.predict(user_input_scaled)

CL = prediction[0][0]
CD = prediction[0][1]
CM = prediction[0][2]

LD = CL / CD

print("\nPredicted Aerodynamic Coefficients")
print("CL =", CL)
print("CD =", CD)
print("CM =", CM)
print("L/D =", LD)

pip install xgboost tensorflow keras streamlit

from xgboost import XGBRegressor
from sklearn.multioutput import MultiOutputRegressor

xgb_model = MultiOutputRegressor(
    XGBRegressor(
        n_estimators=200,
        learning_rate=0.05,
        max_depth=6,
        random_state=42
    )
)

xgb_model.fit(X_train, y_train)

y_pred_xgb = xgb_model.predict(X_test)

rmse_xgb = np.sqrt(mean_squared_error(y_test, y_pred_xgb))

r2_xgb = r2_score(y_test, y_pred_xgb)

print("XGBoost RMSE:", rmse_xgb)
print("XGBoost R2:", r2_xgb)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

nn_model = Sequential()

nn_model.add(Dense(64, activation='relu', input_shape=(3,)))

nn_model.add(Dense(128, activation='relu'))

nn_model.add(Dense(64, activation='relu'))

nn_model.add(Dense(3))

nn_model.compile(
    optimizer='adam',
    loss='mse',
    metrics=['mae']
)

history = nn_model.fit(
    X_train,
    y_train,
    epochs=200,
    batch_size=8,
    validation_split=0.2
)

y_pred_nn = nn_model.predict(X_test)

rmse_nn = np.sqrt(mean_squared_error(y_test, y_pred_nn))

r2_nn = r2_score(y_test, y_pred_nn)

print("Neural Network RMSE:", rmse_nn)
print("Neural Network R2:", r2_nn)

print("Linear Regression R2:", r2_linear)

print("Random Forest R2:", r2_rf)

print("XGBoost R2:", r2_xgb)

print("Neural Network R2:", r2_nn)

joblib.dump(xgb_model, "best_aero_model.pkl")

from sklearn.model_selection import GridSearchCV

!streamlit run app.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py

import streamlit as st
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import plotly.graph_objects as go

#########################################################
# PAGE CONFIG
#########################################################

st.set_page_config(
    page_title="NACA 0012 Predictor",
    layout="wide"
)

st.title("NACA 0012 Aerodynamic AI Predictor")

st.write("Predict CL, CD and CM using NASA aerodynamic dataset")

#########################################################
# NASA DATASET
#########################################################

data = {

    "Mach":[
        0.15,0.15,0.15,0.15,0.15,
        0.20,0.20,0.20,0.20,
        0.25,0.25,0.25,
        0.30,0.30,0.30,
        0.36,0.36,0.36
    ],

    "Reynolds":[
        2000000,2000000,2000000,3940000,5970000,
        2660000,2660000,5950000,8930000,
        3290000,3290000,8920000,
        3900000,3900000,8960000,
        3930000,5880000,8900000
    ],

    "Alpha":[
        -4.25,0.00,4.25,6.00,10.18,
        -4.11,4.27,10.18,13.33,
        -4.00,6.09,12.15,
        -4.11,8.06,12.01,
        -3.97,8.12,10.81
    ],

    "CL":[
        -0.4300,0.0000,0.4450,0.6360,1.0880,
        -0.4265,0.4457,1.0843,1.4162,
        -0.4258,0.6491,1.3285,
        -0.4479,0.8821,1.3442,
        -0.4467,0.9171,1.2265
    ],

    "CD":[
        0.00730,0.00620,0.00670,0.00712,0.01050,
        0.00729,0.00663,0.01044,0.01359,
        0.00736,0.00738,0.01218,
        0.00727,0.01030,0.01336,
        0.00727,0.00865,0.01785
    ],

    "CM":[
        -0.0040,0.0000,0.0040,0.0019,0.0070,
        -0.0034,0.0033,0.0053,0.0116,
        -0.0028,0.0044,0.0109,
        -0.0026,0.0074,0.0147,
        -0.0026,0.0070,0.0233
    ]

}

df = pd.DataFrame(data)

#########################################################
# MACHINE LEARNING
#########################################################

X = df[['Mach','Reynolds','Alpha']]
y = df[['CL','CD','CM']]

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    random_state=42
)

model = RandomForestRegressor(
    n_estimators=300,
    random_state=42
)

model.fit(X_train,y_train)

#########################################################
# SIDEBAR INPUTS
#########################################################

st.sidebar.header("Input Parameters")

mach = st.sidebar.slider(
    "Mach Number",
    0.15,
    0.36,
    0.25
)

reynolds = st.sidebar.number_input(
    "Reynolds Number",
    value=6000000
)

alpha = st.sidebar.slider(
    "Angle of Attack α",
    -5.0,
    15.0,
    8.0
)

#########################################################
# PREDICTION
#########################################################

input_data = np.array([[mach,reynolds,alpha]])

input_scaled = scaler.transform(input_data)

prediction = model.predict(input_scaled)

CL = prediction[0][0]
CD = prediction[0][1]
CM = prediction[0][2]

LD = CL / CD

#########################################################
# DISPLAY RESULTS
#########################################################

col1,col2,col3,col4 = st.columns(4)

col1.metric("CL", round(CL,4))
col2.metric("CD", round(CD,5))
col3.metric("CM", round(CM,4))
col4.metric("L/D", round(LD,2))

#########################################################
# BAR CHART
#########################################################

fig = go.Figure()

fig.add_trace(go.Bar(
    x=["CL","CD","CM"],
    y=[CL,CD,CM]
))

fig.update_layout(
    title="Predicted Aerodynamic Coefficients",
    height=500
)

st.plotly_chart(fig,use_container_width=True)

#########################################################
# DATASET VIEW
#########################################################

st.subheader("NASA Aerodynamic Dataset")

st.dataframe(df)

#########################################################
# ACTUAL VS PREDICTED GRAPH
#########################################################

predictions = model.predict(X_scaled)

fig2 = go.Figure()

fig2.add_trace(go.Scatter(
    x=df["CL"],
    y=predictions[:,0],
    mode='markers'
))

fig2.update_layout(
    title="Actual vs Predicted CL",
    xaxis_title="Actual CL",
    yaxis_title="Predicted CL",
    height=500
)

st.plotly_chart(fig2,use_container_width=True)

!pip install pyngrok

from pyngrok import ngrok

!ngrok config add-authtoken 3D71e7zLRzsHurK9jyKQouFrQVE_7eP1PLvBeKTirMT3cym9d

!streamlit run app.py &>/content/logs.txt &

from pyngrok import ngrok

public_url = ngrok.connect(8501)

print(public_url)

!pip install streamlit pyngrok plotly scikit-learn pandas numpy

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# import numpy as np
# 
# st.set_page_config(page_title="NACA 0012 Predictor")
# 
# st.title("NACA 0012 Aerodynamic Predictor")
# 
# st.write("Real-time aerodynamic coefficient prediction")
# 
# mach = st.slider("Mach Number", 0.15, 0.36, 0.25)
# 
# R = st.number_input("Reynolds Number", value=6000000)
# 
# alpha = st.slider("Angle of Attack", -5.0, 15.0, 8.0)
# 
# # SIMPLE PREDICTION EQUATIONS
# 
# CL = 0.11 * alpha * (1 - mach)
# 
# CD = 0.006 + (CL**2 / 80)
# 
# CM = 0.002 * alpha * mach
# 
# LD = CL / CD
# 
# st.subheader("Predicted Values")
# 
# col1, col2 = st.columns(2)
# 
# col1.metric("CL", round(CL,4))
# col2.metric("CD", round(CD,5))
# 
# col3, col4 = st.columns(2)
# 
# col3.metric("CM", round(CM,4))
# col4.metric("L/D", round(LD,2))
# 
# chart_data = pd.DataFrame({
#     "Coefficient":["CL","CD","CM"],
#     "Value":[CL,CD,CM]
# })
# 
# st.bar_chart(chart_data.set_index("Coefficient"))

!streamlit run app.py &>/content/logs.txt &

!ngrok config add-authtoken 3D71e7zLRzsHurK9jyKQouFrQVE_7eP1PLvBeKTirMT3cym9d

from pyngrok import ngrok

public_url = ngrok.connect(8501)

print(public_url)